
import java.awt.Desktop;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Usuario
 */
public class Calculadora4 extends javax.swing.JFrame {

     private String loquepuso = ""; //lo que pone aca seria el primer numero
    private boolean seusa = true; //si toca un signo hace una operacion
    private boolean haypunto = true; //para ver si hay un punto puesto 
double nro1,nro2, result;
String signo; //para identificar que operacion hacer en cada case

    /**
     *
     */
    public Calculadora4() {
        initComponents();
         try {
            setIconImage(new ImageIcon(getClass().getResource("../iconos/calculadora-cientifica.png")).getImage());}
catch(Exception ex){
}
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        fondologoesc = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        maineim = new javax.swing.JButton();
        mostrador1 = new javax.swing.JTextField();
        paneldebotones = new javax.swing.JPanel();
        borrametodo = new javax.swing.JButton();
        deshacer = new javax.swing.JButton();
        calcporcentaje = new javax.swing.JButton();
        multiplicala = new javax.swing.JButton();
        el7 = new javax.swing.JButton();
        el8 = new javax.swing.JButton();
        el9 = new javax.swing.JButton();
        dividila = new javax.swing.JButton();
        el4 = new javax.swing.JButton();
        el5 = new javax.swing.JButton();
        el6 = new javax.swing.JButton();
        restamela = new javax.swing.JButton();
        el1 = new javax.swing.JButton();
        el2 = new javax.swing.JButton();
        el3 = new javax.swing.JButton();
        sumaaala = new javax.swing.JButton();
        cambiodesigno = new javax.swing.JButton();
        el0 = new javax.swing.JButton();
        elpuntito = new javax.swing.JButton();
        cuantodaesoxd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        fondo.setBackground(new java.awt.Color(0, 0, 0));

        fondologoesc.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/logo esc (2).png"))); // NOI18N

        maineim.setBackground(new java.awt.Color(153, 255, 255));
        maineim.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        maineim.setForeground(new java.awt.Color(0, 0, 0));
        maineim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/masev1 (1).png"))); // NOI18N
        maineim.setToolTipText("");
        maineim.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4));
        maineim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        maineim.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        maineim.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/masev1 (1).png"))); // NOI18N
        maineim.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        maineim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maineimMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maineimMouseExited(evt);
            }
        });
        maineim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maineimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fondologoescLayout = new javax.swing.GroupLayout(fondologoesc);
        fondologoesc.setLayout(fondologoescLayout);
        fondologoescLayout.setHorizontalGroup(
            fondologoescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondologoescLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondologoescLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(maineim, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        fondologoescLayout.setVerticalGroup(
            fondologoescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondologoescLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(maineim, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        mostrador1.setBackground(new java.awt.Color(0, 0, 0));
        mostrador1.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        mostrador1.setForeground(new java.awt.Color(0, 204, 204));
        mostrador1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        mostrador1.setText("0");
        mostrador1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)));
        mostrador1.setName(""); // NOI18N
        mostrador1.setOpaque(true);
        mostrador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrador1ActionPerformed(evt);
            }
        });
        mostrador1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mostrador1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mostrador1KeyTyped(evt);
            }
        });

        paneldebotones.setBackground(new java.awt.Color(0, 0, 0));
        paneldebotones.setLayout(new java.awt.GridLayout(5, 4));

        borrametodo.setBackground(new java.awt.Color(0, 153, 153));
        borrametodo.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        borrametodo.setForeground(new java.awt.Color(255, 255, 255));
        borrametodo.setText("C");
        borrametodo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        borrametodo.setContentAreaFilled(false);
        borrametodo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        borrametodo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondo (1).png"))); // NOI18N
        borrametodo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondo.png"))); // NOI18N
        borrametodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrametodoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                borrametodoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                borrametodoMouseExited(evt);
            }
        });
        borrametodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrametodoActionPerformed(evt);
            }
        });
        paneldebotones.add(borrametodo);

        deshacer.setBackground(new java.awt.Color(0, 153, 153));
        deshacer.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        deshacer.setForeground(new java.awt.Color(255, 255, 255));
        deshacer.setText("CE");
        deshacer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        deshacer.setContentAreaFilled(false);
        deshacer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deshacer.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/deshacer (1).png"))); // NOI18N
        deshacer.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/deshacer.png"))); // NOI18N
        deshacer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deshacerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deshacerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deshacerMouseExited(evt);
            }
        });
        deshacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deshacerActionPerformed(evt);
            }
        });
        paneldebotones.add(deshacer);

        calcporcentaje.setBackground(new java.awt.Color(0, 153, 153));
        calcporcentaje.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        calcporcentaje.setForeground(new java.awt.Color(255, 255, 255));
        calcporcentaje.setText("%");
        calcporcentaje.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        calcporcentaje.setContentAreaFilled(false);
        calcporcentaje.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calcporcentaje.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/porcentaje (1).png"))); // NOI18N
        calcporcentaje.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/porcentaje.png"))); // NOI18N
        calcporcentaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calcporcentajeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                calcporcentajeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                calcporcentajeMouseExited(evt);
            }
        });
        calcporcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcporcentajeActionPerformed(evt);
            }
        });
        paneldebotones.add(calcporcentaje);

        multiplicala.setBackground(new java.awt.Color(0, 153, 153));
        multiplicala.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        multiplicala.setForeground(new java.awt.Color(255, 255, 255));
        multiplicala.setText("x");
        multiplicala.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        multiplicala.setContentAreaFilled(false);
        multiplicala.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        multiplicala.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/multiplicacion (1).png"))); // NOI18N
        multiplicala.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/multiplicacion.png"))); // NOI18N
        multiplicala.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multiplicalaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                multiplicalaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                multiplicalaMouseExited(evt);
            }
        });
        multiplicala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicalaActionPerformed(evt);
            }
        });
        paneldebotones.add(multiplicala);

        el7.setBackground(new java.awt.Color(0, 153, 153));
        el7.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        el7.setForeground(new java.awt.Color(255, 255, 255));
        el7.setText("7");
        el7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        el7.setContentAreaFilled(false);
        el7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        el7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/el7 (1).png"))); // NOI18N
        el7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/el7.png"))); // NOI18N
        el7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                el7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                el7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                el7MouseExited(evt);
            }
        });
        el7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                el7ActionPerformed(evt);
            }
        });
        paneldebotones.add(el7);

        el8.setBackground(new java.awt.Color(0, 153, 153));
        el8.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        el8.setForeground(new java.awt.Color(255, 255, 255));
        el8.setText("8");
        el8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        el8.setContentAreaFilled(false);
        el8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        el8.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/el8 (1).png"))); // NOI18N
        el8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/el8.png"))); // NOI18N
        el8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                el8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                el8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                el8MouseExited(evt);
            }
        });
        el8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                el8ActionPerformed(evt);
            }
        });
        paneldebotones.add(el8);

        el9.setBackground(new java.awt.Color(0, 153, 153));
        el9.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        el9.setForeground(new java.awt.Color(255, 255, 255));
        el9.setText("9");
        el9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        el9.setContentAreaFilled(false);
        el9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        el9.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/el9 (1).png"))); // NOI18N
        el9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/el9.png"))); // NOI18N
        el9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                el9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                el9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                el9MouseExited(evt);
            }
        });
        el9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                el9ActionPerformed(evt);
            }
        });
        paneldebotones.add(el9);

        dividila.setBackground(new java.awt.Color(0, 153, 153));
        dividila.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        dividila.setForeground(new java.awt.Color(255, 255, 255));
        dividila.setText("/");
        dividila.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        dividila.setContentAreaFilled(false);
        dividila.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dividila.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/division (1).png"))); // NOI18N
        dividila.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/division.png"))); // NOI18N
        dividila.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dividilaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dividilaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dividilaMouseExited(evt);
            }
        });
        dividila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividilaActionPerformed(evt);
            }
        });
        paneldebotones.add(dividila);

        el4.setBackground(new java.awt.Color(0, 153, 153));
        el4.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        el4.setForeground(new java.awt.Color(255, 255, 255));
        el4.setText("4");
        el4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        el4.setContentAreaFilled(false);
        el4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        el4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/en4 (1).png"))); // NOI18N
        el4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/en4.png"))); // NOI18N
        el4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                el4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                el4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                el4MouseExited(evt);
            }
        });
        el4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                el4ActionPerformed(evt);
            }
        });
        paneldebotones.add(el4);

        el5.setBackground(new java.awt.Color(0, 153, 153));
        el5.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        el5.setForeground(new java.awt.Color(255, 255, 255));
        el5.setText("5");
        el5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        el5.setContentAreaFilled(false);
        el5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        el5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/el5 (1).png"))); // NOI18N
        el5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/el5.png"))); // NOI18N
        el5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                el5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                el5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                el5MouseExited(evt);
            }
        });
        el5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                el5ActionPerformed(evt);
            }
        });
        paneldebotones.add(el5);

        el6.setBackground(new java.awt.Color(0, 153, 153));
        el6.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        el6.setForeground(new java.awt.Color(255, 255, 255));
        el6.setText("6");
        el6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        el6.setContentAreaFilled(false);
        el6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        el6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/el6 (1).png"))); // NOI18N
        el6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/el6.png"))); // NOI18N
        el6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                el6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                el6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                el6MouseExited(evt);
            }
        });
        el6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                el6ActionPerformed(evt);
            }
        });
        paneldebotones.add(el6);

        restamela.setBackground(new java.awt.Color(0, 153, 153));
        restamela.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        restamela.setForeground(new java.awt.Color(255, 255, 255));
        restamela.setText("-");
        restamela.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        restamela.setContentAreaFilled(false);
        restamela.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        restamela.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menos (1).png"))); // NOI18N
        restamela.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menos.png"))); // NOI18N
        restamela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restamelaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                restamelaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                restamelaMouseExited(evt);
            }
        });
        restamela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restamelaActionPerformed(evt);
            }
        });
        paneldebotones.add(restamela);

        el1.setBackground(new java.awt.Color(0, 153, 153));
        el1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        el1.setForeground(new java.awt.Color(255, 255, 255));
        el1.setText("1");
        el1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        el1.setContentAreaFilled(false);
        el1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        el1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/el1 (1).png"))); // NOI18N
        el1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/el1.png"))); // NOI18N
        el1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                el1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                el1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                el1MouseExited(evt);
            }
        });
        el1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                el1ActionPerformed(evt);
            }
        });
        paneldebotones.add(el1);

        el2.setBackground(new java.awt.Color(0, 153, 153));
        el2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        el2.setForeground(new java.awt.Color(255, 255, 255));
        el2.setText("2");
        el2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        el2.setContentAreaFilled(false);
        el2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        el2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/el2 (1).png"))); // NOI18N
        el2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/el2.png"))); // NOI18N
        el2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                el2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                el2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                el2MouseExited(evt);
            }
        });
        el2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                el2ActionPerformed(evt);
            }
        });
        paneldebotones.add(el2);

        el3.setBackground(new java.awt.Color(0, 153, 153));
        el3.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        el3.setForeground(new java.awt.Color(255, 255, 255));
        el3.setText("3");
        el3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        el3.setContentAreaFilled(false);
        el3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        el3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/el3 (1).png"))); // NOI18N
        el3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/el3.png"))); // NOI18N
        el3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                el3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                el3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                el3MouseExited(evt);
            }
        });
        el3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                el3ActionPerformed(evt);
            }
        });
        paneldebotones.add(el3);

        sumaaala.setBackground(new java.awt.Color(0, 153, 153));
        sumaaala.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        sumaaala.setForeground(new java.awt.Color(255, 255, 255));
        sumaaala.setText("+");
        sumaaala.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        sumaaala.setContentAreaFilled(false);
        sumaaala.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sumaaala.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/mas (1).png"))); // NOI18N
        sumaaala.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/mas.png"))); // NOI18N
        sumaaala.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sumaaalaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sumaaalaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sumaaalaMouseExited(evt);
            }
        });
        sumaaala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaaalaActionPerformed(evt);
            }
        });
        paneldebotones.add(sumaaala);

        cambiodesigno.setBackground(new java.awt.Color(0, 153, 153));
        cambiodesigno.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        cambiodesigno.setForeground(new java.awt.Color(255, 255, 255));
        cambiodesigno.setText("-/+");
        cambiodesigno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        cambiodesigno.setContentAreaFilled(false);
        cambiodesigno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cambiodesigno.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/calculo (1).png"))); // NOI18N
        cambiodesigno.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/calculo.png"))); // NOI18N
        cambiodesigno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cambiodesignoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cambiodesignoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cambiodesignoMouseExited(evt);
            }
        });
        cambiodesigno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiodesignoActionPerformed(evt);
            }
        });
        paneldebotones.add(cambiodesigno);

        el0.setBackground(new java.awt.Color(0, 153, 153));
        el0.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        el0.setForeground(new java.awt.Color(255, 255, 255));
        el0.setText("0");
        el0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        el0.setContentAreaFilled(false);
        el0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        el0.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/el0 (1).png"))); // NOI18N
        el0.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/el0.png"))); // NOI18N
        el0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                el0MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                el0MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                el0MouseExited(evt);
            }
        });
        el0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                el0ActionPerformed(evt);
            }
        });
        paneldebotones.add(el0);

        elpuntito.setBackground(new java.awt.Color(0, 153, 153));
        elpuntito.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        elpuntito.setForeground(new java.awt.Color(255, 255, 255));
        elpuntito.setText(".");
        elpuntito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        elpuntito.setContentAreaFilled(false);
        elpuntito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        elpuntito.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/puntillo (1).png"))); // NOI18N
        elpuntito.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/puntillo.png"))); // NOI18N
        elpuntito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elpuntitoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                elpuntitoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                elpuntitoMouseExited(evt);
            }
        });
        elpuntito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elpuntitoActionPerformed(evt);
            }
        });
        paneldebotones.add(elpuntito);

        cuantodaesoxd.setBackground(new java.awt.Color(0, 153, 153));
        cuantodaesoxd.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        cuantodaesoxd.setForeground(new java.awt.Color(255, 255, 255));
        cuantodaesoxd.setText("=");
        cuantodaesoxd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        cuantodaesoxd.setContentAreaFilled(false);
        cuantodaesoxd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cuantodaesoxd.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/igual (1).png"))); // NOI18N
        cuantodaesoxd.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/igual.png"))); // NOI18N
        cuantodaesoxd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuantodaesoxdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cuantodaesoxdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cuantodaesoxdMouseExited(evt);
            }
        });
        cuantodaesoxd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuantodaesoxdActionPerformed(evt);
            }
        });
        paneldebotones.add(cuantodaesoxd);

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mostrador1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fondologoesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fondoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(paneldebotones, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                    .addGap(274, 274, 274)))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondologoesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mostrador1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                    .addContainerGap(103, Short.MAX_VALUE)
                    .addComponent(paneldebotones, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        getContentPane().add(fondo);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maineimMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maineimMouseEntered
        maineim.setText("Ir a Linkedin");
                //aca cuando le asomas el mause aparece el texto
    }//GEN-LAST:event_maineimMouseEntered

    private void maineimMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maineimMouseExited
        maineim.setText(""); //aca cuando le sacas el mause te lo borra pa que vuelva como estaba
    }//GEN-LAST:event_maineimMouseExited

    private void maineimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maineimActionPerformed
        try{ Desktop.getDesktop().browse(new URI("https://www.linkedin.com/in/marcelo-alejandro-asevedo/"));
        }catch(HeadlessException | IOException | URISyntaxException e){
            System.out.println(e);
            //esto sirve para abrir links, lo que puedo hacer tambien es adaptarlo a un jtex para que una persona ponga un link y lo abra, pero como es una calculadora para que voy a necesitar eso no? xd
        }

    }//GEN-LAST:event_maineimActionPerformed

    private void mostrador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrador1ActionPerformed

    private void mostrador1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mostrador1KeyPressed
        if (evt.getKeyChar()=='+'){
           
                nro1=Double.parseDouble(mostrador1.getText());
                signo="+";
                //se guarda el signo para despues configurar el igual para indicar la operacion para hacer
                mostrador1.setText("");
                haypunto=true;
                seusa = false;
        }
         if (evt.getKeyChar()=='-'){
           
                nro1=Double.parseDouble(mostrador1.getText());
                signo="-";
                //se guarda el signo para despues configurar el igual para indicar la operacion para hacer
                mostrador1.setText("");
                haypunto=true;
                seusa = false;
        }
          if (evt.getKeyChar()=='/'){
           
                nro1=Double.parseDouble(mostrador1.getText());
                signo="/";
                //se guarda el signo para despues configurar el igual para indicar la operacion para hacer
                mostrador1.setText("");
                haypunto=true;
                seusa = false;
        }
           if (evt.getKeyChar()=='*'){
           
                nro1=Double.parseDouble(mostrador1.getText());
                signo="*";
                //se guarda el signo para despues configurar el igual para indicar la operacion para hacer
                mostrador1.setText("");
                haypunto=true;
                seusa = false;
        }
      if (evt.getKeyChar()==KeyEvent.VK_ENTER){
           switch(signo){
            case "+":
            nro2=Double.parseDouble(mostrador1.getText());
            result=(double)nro1+nro2;

            mostrador1.setText(Double.toString(result));
                nro1=result;
            break; //para cerrar el caso xd
            // el set tex me indica lo que quiero que aparezca en el mostrador, si bien se trabaja con doubl se pone el to string porque es lo que muestra, y entre parentesis el resultado y lo cambie a un string para q se muestre
            case "*":
            nro2=Double.parseDouble(mostrador1.getText());
            result=(double)nro1*nro2;
            mostrador1.setText(Double.toString(result));
                loquepuso=Double.toString(result);
                nro1=result;
            break;
            case "-":
            nro2=Double.parseDouble(mostrador1.getText());
            result=(double)nro1-nro2;
           mostrador1.setText(Double.toString(result));
                loquepuso=Double.toString(result);
                nro1=result;
            break;
            case "/":
            nro2=Double.parseDouble(mostrador1.getText());
            if (nro2 == 0){
                mostrador1.setText("No se divide por 0");
              
            } else {
                result=(double)nro1/nro2;
              mostrador1.setText(Double.toString(result));
                loquepuso=Double.toString(result);
                nro1=result;
                break;
            }

        }
        }
      
    }//GEN-LAST:event_mostrador1KeyPressed

    private void mostrador1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mostrador1KeyTyped
        if(!Character.isDigit(evt.getKeyChar())&& evt.getKeyChar() != '.'){ //pregunta si hay un digito(sea letra o simbolos) y si tiene un punto, si es una letra la borra en la otra linea y si tiene un punto lo deja
            evt.consume();
        }
        if (evt.getKeyChar() == '.' && mostrador1.getText().contains(".")){ //aca pregunta si hay un punto y si ya hay un punto no escribe otro
            evt.consume();
        }

    }//GEN-LAST:event_mostrador1KeyTyped

    private void borrametodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrametodoMouseClicked
        borrametodo.setText("");
    }//GEN-LAST:event_borrametodoMouseClicked

    private void borrametodoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrametodoMouseEntered
        borrametodo.setText("");
    }//GEN-LAST:event_borrametodoMouseEntered

    private void borrametodoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrametodoMouseExited
        borrametodo.setText("C");
    }//GEN-LAST:event_borrametodoMouseExited

    private void borrametodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrametodoActionPerformed
        mostrador1.setText("0");
        loquepuso="";
        seusa=true; //es para "activar" el boton de suma resta mult div, parece que esta al p2, tengo que revisarlo, pero anda la calcu, de ultima veo que onda
        haypunto=true; //para ver si hay un punto y que no escriba otro
    }//GEN-LAST:event_borrametodoActionPerformed

    private void deshacerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deshacerMouseClicked
        deshacer.setText("");
    }//GEN-LAST:event_deshacerMouseClicked

    private void deshacerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deshacerMouseEntered
        deshacer.setText("");
    }//GEN-LAST:event_deshacerMouseEntered

    private void deshacerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deshacerMouseExited
        deshacer.setText("CE");
    }//GEN-LAST:event_deshacerMouseExited

    private void deshacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deshacerActionPerformed
        int todoloquepuso;
        todoloquepuso=loquepuso.length(); //esto es para indicar el tamaño de todo lo que pudo por ejemplo puso 100 y son 3 caracteres
        if(todoloquepuso>0){
            if(todoloquepuso == 1){  //si hay un solo ¿digito? me pone un cero
                loquepuso="0";
            } else { //sino, es decir si hay mas de un digito me borra el ultimo
                loquepuso = loquepuso.substring(0,loquepuso.length() -1); //con esto a medida que va tocando el boton borra lo ultimo que aparece en el jtext
            }
            mostrador1.setText(loquepuso); //una vez que termina con toda esa webada anterior muestra como queda xd
        }
    }//GEN-LAST:event_deshacerActionPerformed

    private void calcporcentajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcporcentajeMouseClicked
        calcporcentaje.setText("");
    }//GEN-LAST:event_calcporcentajeMouseClicked

    private void calcporcentajeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcporcentajeMouseEntered
        calcporcentaje.setText("");
    }//GEN-LAST:event_calcporcentajeMouseEntered

    private void calcporcentajeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcporcentajeMouseExited
        calcporcentaje.setText("%");
    }//GEN-LAST:event_calcporcentajeMouseExited

    private void calcporcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcporcentajeActionPerformed
        switch(signo){ //segun signo, hace todo lo que sigue, por ejemplo si es el mas suma y asi...
            case "+":
            nro2=Double.parseDouble(mostrador1.getText());
            result=(double)nro1*((nro2/100)+1);

            mostrador1.setText(Double.toString(result));
                loquepuso=Double.toString(result);
            break;
            // el set tex me indica lo que quiero que aparezca en el mostrador, si bien se trabaja con doubl se pone el to string porque es lo que muestra, y entre parentesis el resultado y lo cambie a un string para q se muestre
            case "-":
            nro2=Double.parseDouble(mostrador1.getText());
            result=(double)nro1-(nro1*(nro2/100));
            mostrador1.setText(Double.toString(result));
                loquepuso=Double.toString(result);
            break;
        }
    }//GEN-LAST:event_calcporcentajeActionPerformed

    private void multiplicalaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplicalaMouseClicked
        multiplicala.setText("");
    }//GEN-LAST:event_multiplicalaMouseClicked

    private void multiplicalaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplicalaMouseEntered
        multiplicala.setText("");
    }//GEN-LAST:event_multiplicalaMouseEntered

    private void multiplicalaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplicalaMouseExited
        multiplicala.setText("x");
    }//GEN-LAST:event_multiplicalaMouseExited

    private void multiplicalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicalaActionPerformed
        if (seusa==true){
            nro1=Double.parseDouble(mostrador1.getText()); //asigno lo que puso al nro1
            signo="*";
            //se guarda el signo para despues configurar el igual para indicar la operacion para hacer
            mostrador1.setText("");
            haypunto=true;
            seusa = false;
        }
    }//GEN-LAST:event_multiplicalaActionPerformed

    private void el7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_el7MouseClicked
        el7.setText("");
    }//GEN-LAST:event_el7MouseClicked

    private void el7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_el7MouseEntered
        el7.setText("");
    }//GEN-LAST:event_el7MouseEntered

    private void el7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_el7MouseExited
        el7.setText("7");
    }//GEN-LAST:event_el7MouseExited

    private void el7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_el7ActionPerformed
        if (mostrador1.getText().equals("")){ //el gettex tengo entendido que es para ver lo que hay en el jtext, aca pregunta si ahi no hay nada que ponga un 7 y sino que agregue otro
            loquepuso = "7";
        } else {
            loquepuso += "7"; //el += es para agregar
        }
        mostrador1.setText(loquepuso);
        seusa = true;
    }//GEN-LAST:event_el7ActionPerformed

    private void el8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_el8MouseClicked
        el8.setText("");
    }//GEN-LAST:event_el8MouseClicked

    private void el8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_el8MouseEntered
        el8.setText("");
    }//GEN-LAST:event_el8MouseEntered

    private void el8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_el8MouseExited
        el8.setText("8");
    }//GEN-LAST:event_el8MouseExited

    private void el8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_el8ActionPerformed
        if (mostrador1.getText().equals("")){
            loquepuso = "8";
        } else {
            loquepuso += "8";
        }
        mostrador1.setText(loquepuso);
        seusa = true;
    }//GEN-LAST:event_el8ActionPerformed

    private void el9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_el9MouseClicked
        el9.setText("");
    }//GEN-LAST:event_el9MouseClicked

    private void el9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_el9MouseEntered
        el9.setText("");
    }//GEN-LAST:event_el9MouseEntered

    private void el9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_el9MouseExited
        el9.setText("9");
    }//GEN-LAST:event_el9MouseExited

    private void el9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_el9ActionPerformed
        if (mostrador1.getText().equals("")){
            loquepuso = "9";
        } else {
            loquepuso += "9";
        }
        mostrador1.setText(loquepuso);
        seusa = true;
    }//GEN-LAST:event_el9ActionPerformed

    private void dividilaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dividilaMouseClicked
        dividila.setText("");
    }//GEN-LAST:event_dividilaMouseClicked

    private void dividilaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dividilaMouseEntered
        dividila.setText("");
    }//GEN-LAST:event_dividilaMouseEntered

    private void dividilaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dividilaMouseExited
        dividila.setText("/");
    }//GEN-LAST:event_dividilaMouseExited

    private void dividilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dividilaActionPerformed
        if (seusa==true){
            nro1=Double.parseDouble(mostrador1.getText());
            signo="/";
            //se guarda el signo para despues configurar el igual para indicar la operacion para hacer
            mostrador1.setText("");
            haypunto=true;
            seusa = false;
        }
    }//GEN-LAST:event_dividilaActionPerformed

    private void el4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_el4MouseClicked
        el4.setText("");
    }//GEN-LAST:event_el4MouseClicked

    private void el4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_el4MouseEntered
        el4.setText("");
    }//GEN-LAST:event_el4MouseEntered

    private void el4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_el4MouseExited
        el4.setText("4");
    }//GEN-LAST:event_el4MouseExited

    private void el4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_el4ActionPerformed
        if (mostrador1.getText().equals("")){
            loquepuso = "4";
        } else {
            loquepuso += "4";
        }
        mostrador1.setText(loquepuso);
        seusa = true;
    }//GEN-LAST:event_el4ActionPerformed

    private void el5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_el5MouseClicked
        el5.setText("");
    }//GEN-LAST:event_el5MouseClicked

    private void el5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_el5MouseEntered
        el5.setText("");
    }//GEN-LAST:event_el5MouseEntered

    private void el5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_el5MouseExited
        el5.setText("5");
    }//GEN-LAST:event_el5MouseExited

    private void el5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_el5ActionPerformed
        if (mostrador1.getText().equals("")){
            loquepuso = "5";
        } else {
            loquepuso += "5";
        }
        mostrador1.setText(loquepuso);
        seusa = true;

    }//GEN-LAST:event_el5ActionPerformed

    private void el6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_el6MouseClicked
        el6.setText("");
    }//GEN-LAST:event_el6MouseClicked

    private void el6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_el6MouseEntered
        el6.setText("");
    }//GEN-LAST:event_el6MouseEntered

    private void el6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_el6MouseExited
        el6.setText("6");
    }//GEN-LAST:event_el6MouseExited

    private void el6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_el6ActionPerformed
        if (mostrador1.getText().equals("")){
            loquepuso = "6";
        } else {
            loquepuso += "6";
        }
        mostrador1.setText(loquepuso);
        seusa = true;
    }//GEN-LAST:event_el6ActionPerformed

    private void restamelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restamelaMouseClicked
        restamela.setText("");
    }//GEN-LAST:event_restamelaMouseClicked

    private void restamelaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restamelaMouseEntered
        restamela.setText("");
    }//GEN-LAST:event_restamelaMouseEntered

    private void restamelaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restamelaMouseExited
        restamela.setText("-");
    }//GEN-LAST:event_restamelaMouseExited

    private void restamelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restamelaActionPerformed
        if (seusa==true){
            nro1=Double.parseDouble(mostrador1.getText());
            signo="-";
            //se guarda el signo para despues configurar el igual para indicar la operacion para hacer
            mostrador1.setText("");
            haypunto=true;
            seusa = false;
        }
    }//GEN-LAST:event_restamelaActionPerformed

    private void el1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_el1MouseClicked
        el1.setText("");
    }//GEN-LAST:event_el1MouseClicked

    private void el1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_el1MouseEntered
        el1.setText("");
    }//GEN-LAST:event_el1MouseEntered

    private void el1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_el1MouseExited
        el1.setText("1");
    }//GEN-LAST:event_el1MouseExited

    private void el1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_el1ActionPerformed
        if (mostrador1.getText().equals("")){
            loquepuso = "1";
        } else {
            loquepuso += "1";
        }
        mostrador1.setText(loquepuso);
        seusa = true;
    }//GEN-LAST:event_el1ActionPerformed

    private void el2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_el2MouseClicked
        el2.setText("");
    }//GEN-LAST:event_el2MouseClicked

    private void el2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_el2MouseEntered
        el2.setText("");
    }//GEN-LAST:event_el2MouseEntered

    private void el2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_el2MouseExited
        el2.setText("2");
    }//GEN-LAST:event_el2MouseExited

    private void el2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_el2ActionPerformed
        if (mostrador1.getText().equals("")){
            loquepuso = "2";
        } else {
            loquepuso += "2";
        }
        mostrador1.setText(loquepuso);
        seusa = true;
    }//GEN-LAST:event_el2ActionPerformed

    private void el3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_el3MouseClicked
        el3.setText("");
    }//GEN-LAST:event_el3MouseClicked

    private void el3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_el3MouseEntered
        el3.setText("");
    }//GEN-LAST:event_el3MouseEntered

    private void el3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_el3MouseExited
        el3.setText("3");
    }//GEN-LAST:event_el3MouseExited

    private void el3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_el3ActionPerformed
        if (mostrador1.getText().equals("")){
            loquepuso = "3";
        } else {
            loquepuso += "3";
        }
        mostrador1.setText(loquepuso);
        seusa = true;
    }//GEN-LAST:event_el3ActionPerformed

    private void sumaaalaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumaaalaMouseClicked
        sumaaala.setText("");
    }//GEN-LAST:event_sumaaalaMouseClicked

    private void sumaaalaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumaaalaMouseEntered
        sumaaala.setText("");
    }//GEN-LAST:event_sumaaalaMouseEntered

    private void sumaaalaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumaaalaMouseExited
        sumaaala.setText("+");
    }//GEN-LAST:event_sumaaalaMouseExited

    private void sumaaalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaaalaActionPerformed
        if (seusa==true){
            nro1=Double.parseDouble(mostrador1.getText());
            signo="+";
            //se guarda el signo para despues configurar el igual para indicar la operacion para hacer
            mostrador1.setText("");
            haypunto=true;
            seusa = false;
        }
    }//GEN-LAST:event_sumaaalaActionPerformed

    private void cambiodesignoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cambiodesignoMouseClicked
        cambiodesigno.setText("");
    }//GEN-LAST:event_cambiodesignoMouseClicked

    private void cambiodesignoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cambiodesignoMouseEntered
        cambiodesigno.setText("");
    }//GEN-LAST:event_cambiodesignoMouseEntered

    private void cambiodesignoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cambiodesignoMouseExited
        cambiodesigno.setText("-/+");
    }//GEN-LAST:event_cambiodesignoMouseExited

    private void cambiodesignoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiodesignoActionPerformed
        if(loquepuso.charAt(0) != '-'){  //loque hace aca es que si lo que puso e distinto a menos entonces le mete un menos y si no un mas
            loquepuso = "-" + loquepuso;
        } else{
            loquepuso = loquepuso.substring(1,loquepuso.length()); //ese 1 hace que recorte el menos y quede positivo

        }
        mostrador1.setText(loquepuso);
    }//GEN-LAST:event_cambiodesignoActionPerformed

    private void el0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_el0MouseClicked
        el0.setText("");
    }//GEN-LAST:event_el0MouseClicked

    private void el0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_el0MouseEntered
        el0.setText("");
    }//GEN-LAST:event_el0MouseEntered

    private void el0MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_el0MouseExited
        el0.setText("0");
    }//GEN-LAST:event_el0MouseExited

    private void el0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_el0ActionPerformed
        if (mostrador1.getText().equals("")){
            loquepuso = "0";
        } else {
            loquepuso += "0";
        }
        mostrador1.setText(loquepuso);
        seusa = true;
    }//GEN-LAST:event_el0ActionPerformed

    private void elpuntitoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elpuntitoMouseClicked
        elpuntito.setText("");
    }//GEN-LAST:event_elpuntitoMouseClicked

    private void elpuntitoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elpuntitoMouseEntered
        elpuntito.setText("");
    }//GEN-LAST:event_elpuntitoMouseEntered

    private void elpuntitoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elpuntitoMouseExited
        elpuntito.setText(".");
    }//GEN-LAST:event_elpuntitoMouseExited

    private void elpuntitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elpuntitoActionPerformed
        if (haypunto==true){   //haypunto=true;

            if (loquepuso.equals("")){
                loquepuso="0.";
                mostrador1.setText(loquepuso);
                haypunto=false;

            }else{if(mostrador1.getText().contains(".")){
                //loquepuso=mostrador1.getText()+""; //con esto quiero que no me ponga el punto si ya hay uno, teng que hacerlo andar o ver un videito de 1h por esto xd
                haypunto=false;
            }else{
                loquepuso+=".";
                mostrador1.setText(loquepuso);
                haypunto=false;
            }
        }
        }
    }//GEN-LAST:event_elpuntitoActionPerformed

    private void cuantodaesoxdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuantodaesoxdMouseClicked
        cuantodaesoxd.setText("");
    }//GEN-LAST:event_cuantodaesoxdMouseClicked

    private void cuantodaesoxdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuantodaesoxdMouseEntered
        cuantodaesoxd.setText("");
    }//GEN-LAST:event_cuantodaesoxdMouseEntered

    private void cuantodaesoxdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuantodaesoxdMouseExited
        cuantodaesoxd.setText("=");
    }//GEN-LAST:event_cuantodaesoxdMouseExited

    private void cuantodaesoxdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuantodaesoxdActionPerformed
        switch(signo){
            case "+":
            nro2=Double.parseDouble(mostrador1.getText());
            result=(double)nro1+nro2;

            mostrador1.setText(Double.toString(result));
                nro1=result;
            break; //para cerrar el caso xd
            // el set tex me indica lo que quiero que aparezca en el mostrador, si bien se trabaja con doubl se pone el to string porque es lo que muestra, y entre parentesis el resultado y lo cambie a un string para q se muestre
            case "*":
            nro2=Double.parseDouble(mostrador1.getText());
            result=(double)nro1*nro2;
            mostrador1.setText(Double.toString(result));
                loquepuso=Double.toString(result);
                nro1=result;
            break;
            case "-":
            nro2=Double.parseDouble(mostrador1.getText());
            result=(double)nro1-nro2;
           mostrador1.setText(Double.toString(result));
                loquepuso=Double.toString(result);
                nro1=result;
            break;
            case "/":
            nro2=Double.parseDouble(mostrador1.getText());
            if (nro2 == 0){
                mostrador1.setText("No se divide por 0");
              
            } else {
                result=(double)nro1/nro2;
              mostrador1.setText(Double.toString(result));
                loquepuso=Double.toString(result);
                nro1=result;
                break;
            }

        }
    }//GEN-LAST:event_cuantodaesoxdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrametodo;
    private javax.swing.JButton calcporcentaje;
    private javax.swing.JButton cambiodesigno;
    private javax.swing.JButton cuantodaesoxd;
    private javax.swing.JButton deshacer;
    private javax.swing.JButton dividila;
    private javax.swing.JButton el0;
    private javax.swing.JButton el1;
    private javax.swing.JButton el2;
    private javax.swing.JButton el3;
    private javax.swing.JButton el4;
    private javax.swing.JButton el5;
    private javax.swing.JButton el6;
    private javax.swing.JButton el7;
    private javax.swing.JButton el8;
    private javax.swing.JButton el9;
    private javax.swing.JButton elpuntito;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel fondologoesc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton maineim;
    private javax.swing.JTextField mostrador1;
    private javax.swing.JButton multiplicala;
    private javax.swing.JPanel paneldebotones;
    private javax.swing.JButton restamela;
    private javax.swing.JButton sumaaala;
    // End of variables declaration//GEN-END:variables
}
